on: [push]
name: Test
jobs:
  test:
    runs-on: "self-hosted"
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.19.x"
    - uses: actions/checkout@v3
    - run: go test ./...